export const legalServices = [
  {
    id: 'representations-local-statutory-organizations',
    title: 'Representations to Local Statutory Organizations',
    short: 'Strategic representation and advisory support for local statutory bodies and public institutions.',
    long: 'We support statutory organizations with governance-focused legal advisory, policy interpretation, and operational guidance designed to strengthen institutional performance and compliance.',
    features: ['Institutional advisory', 'Governance support', 'Regulatory interpretation', 'Policy alignment'],
    icon: 'Building2',
  },
  {
    id: 'corporate-legal-services',
    title: 'Corporate Legal Services',
    short: 'End-to-end legal guidance for companies, boards, and investors across critical corporate decisions.',
    long: 'Our Corporate Legal Services assist businesses with formation, board counsel, governance, restructuring, and sustainable corporate continuity planning tailored to their commercial goals.',
    features: ['Entity formation', 'Board advisory', 'Corporate governance', 'Business structuring'],
    icon: 'Building2',
  },
  {
    id: 'compliance-due-diligence-services',
    title: 'Compliance and Due Diligence Services',
    short: 'Practical compliance frameworks and risk-focused diligence to protect businesses before, during, and after transactions.',
    long: 'We help organizations identify, assess, and manage legal and regulatory risk through tailored compliance programs, diligence reviews, and risk mitigation advice.',
    features: ['Regulatory assessment', 'Due diligence reviews', 'Risk mitigation', 'Control design'],
    icon: 'ShieldCheck',
  },
  {
    id: 'obtaining-licenses-and-permits',
    title: 'Obtaining Licenses and Permits',
    short: 'Support for securing the approvals and registrations businesses need to operate lawfully and efficiently.',
    long: 'From applications to approvals, we help clients navigate licensing and permit requirements with greater confidence, speed, and compliance clarity.',
    features: ['Application support', 'Regulatory coordination', 'Permit strategy', 'Approval tracking'],
    icon: 'ShieldCheck',
  },
  {
    id: 'provision-of-statutory-services',
    title: 'Provision of Statutory Services',
    short: 'Nominee Director services, company secretarial support, and registered office facilities.',
    long: 'We provide dependable statutory support services that help organizations maintain compliance, operational continuity, and professional governance standards.',
    features: ['Nominee Director services', 'Company secretarial support', 'Registered office facilities', 'Statutory compliance support'],
    icon: 'Scale',
  },
  {
    id: 'notarizations',
    title: 'Notarizations',
    short: 'Reliable notarization services for formal legal instruments, declarations, and transactional documents.',
    long: 'Our notarization services ensure that important legal documents are properly authenticated and executed to meet domestic and cross-border requirements.',
    features: ['Document authentication', 'Execution support', 'Formal certification', 'Cross-border document readiness'],
    icon: 'Scale',
  },
  {
    id: 'corporate-liquidations',
    title: 'Corporate Liquidations',
    short: 'Structured legal guidance for winding up corporate entities with administrative precision.',
    long: 'We advise on orderly liquidation processes, creditor protection, statutory obligations, and the practical steps needed to close entities responsibly.',
    features: ['Winding-up strategy', 'Creditor coordination', 'Regulatory process support', 'Asset distribution advice'],
    icon: 'ArrowRightLeft',
  },
  {
    id: 'shareholder-structuring-and-agreements',
    title: 'Shareholder Structuring and Agreements',
    short: 'Practical shareholder structuring advice and robust agreement drafting for ownership arrangements.',
    long: 'We help founders and investors design effective ownership structures and negotiate agreements that balance operational flexibility with legal certainty.',
    features: ['Shareholder agreement drafting', 'Ownership structuring', 'Investor protections', 'Governance alignment'],
    icon: 'Building2',
  },
  {
    id: 'immigration-support',
    title: 'Immigration Support',
    short: 'Professional guidance on immigration pathways, permit applications, and compliance obligations.',
    long: 'We support individuals and organizations with immigration-related legal strategy, documentation, and compliance coordination for successful cross-border mobility.',
    features: ['Immigration strategy', 'Document preparation', 'Permit guidance', 'Compliance support'],
    icon: 'ShieldCheck',
  },
  {
    id: 'employment-and-labour-issues',
    title: 'Employment and Labour Issues',
    short: 'Support for workplace disputes, policy review, compliance, and employment risk management.',
    long: 'Our employment advisory helps organizations manage workforce matters prudently, from drafting policies to addressing sensitive labour and workplace issues.',
    features: ['Employment policies', 'Labour advisory', 'Workplace dispute support', 'Compliance reviews'],
    icon: 'Scale',
  },
  {
    id: 'litigation-advisory',
    title: 'Litigation Advisory',
    short: 'Strategic guidance before, during, and after disputes to protect business interests and manage risk.',
    long: 'We provide measured and commercially focused guidance for dispute avoidance, litigation preparation, and risk-based resolution strategies.',
    features: ['Dispute strategy', 'Pre-litigation review', 'Evidence preparation', 'Resolution planning'],
    icon: 'Scale',
  },
  {
    id: 'sec-advisors',
    title: 'SEC Advisors',
    short: 'Practical support for securities-related legal, disclosure, and regulatory processes.',
    long: 'Our SEC advisory services help clients navigate disclosure obligations, reporting expectations, and securities-related compliance requirements with confidence.',
    features: ['Regulatory advice', 'Disclosure support', 'Reporting guidance', 'Compliance alignment'],
    icon: 'ShieldCheck',
  },
  {
    id: 'drafting-policy-and-legislation',
    title: 'Drafting Policy and Legislation for Government of Ghana and its Agencies',
    short: 'High-quality policy and legislation drafting support for public-sector institutions and agencies.',
    long: 'We support government institutions with technically sound drafting, legal analysis, and reform-oriented policy development that mirrors national priorities and statutory needs.',
    features: ['Policy drafting', 'Legislative drafting', 'Public sector reform support', 'Administrative legal drafting'],
    icon: 'Building2',
  },
  {
    id: 'justice-human-rights-public-sector-reform',
    title: 'Justice (Human Rights and Public Sector Reform)',
    short: 'Legal advisory focused on justice reform, human rights, and public-sector accountability.',
    long: 'We contribute legal and strategic insight to human rights initiatives, justice-sector reform, and governance improvements in the public interest.',
    features: ['Human rights advisory', 'Justice reform support', 'Public sector accountability', 'Institutional strengthening'],
    icon: 'Scale',
  },
  {
    id: 'legal-research-professional-opinions',
    title: 'Legal Research',
    short: 'Developing arguments and proffering professional opinions and recommendations.',
    long: 'Our legal research capability delivers rigorous analysis, persuasive argument development, and practical opinions tailored to client needs and regulatory realities.',
    features: ['Issue analysis', 'Argument development', 'Professional opinions', 'Recommendations'],
    icon: 'BookOpen',
  },
  {
    id: 'transaction-advisory-services',
    title: 'Transaction Advisory Services',
    short: 'Commercially focused advisory for transactions, negotiations, and business-critical agreements.',
    long: 'We advise on complex transactions by combining legal rigor with commercial judgment, helping clients structure and execute deals with clarity and confidence.',
    features: ['Transaction strategy', 'Negotiation support', 'Commercial review', 'Implementation planning'],
    icon: 'ArrowRightLeft',
  },
  {
    id: 'drafting-reviewing-contracts-memoranda',
    title: 'Drafting and Reviewing Contracts and Legal Memoranda',
    short: 'Clear drafting, practical review, and negotiation support for contracts and legal memoranda.',
    long: 'We draft, review, and refine contracts and legal memoranda to reduce ambiguity, manage risk, and support sound business decision-making.',
    features: ['Contract drafting', 'Legal memorandum support', 'Negotiation support', 'Risk-focused review'],
    icon: 'Scale',
  },
  {
    id: 'negotiating-agreements',
    title: 'Negotiating Agreements',
    short: 'Skilled negotiation assistance to protect priorities, reduce exposure, and secure favorable outcomes.',
    long: 'We help parties structure, negotiate, and manage agreements with a focus on clarity, leverage, and practical commercial outcomes.',
    features: ['Negotiation strategy', 'Term alignment', 'Risk allocation', 'Outcome optimization'],
    icon: 'ArrowRightLeft',
  },
];

export const advisoryServices = [
  {
    id: 'pre-establishment-start-up-advisory',
    title: 'Pre-establishment and Start-up Advisory Services',
    short: 'Practical advisory to help new ventures launch with clarity, compliance, and strong positioning.',
    long: 'We guide founders and entrepreneurs through the early stages of business creation, from opportunity assessment and structure selection to launch readiness and operational planning.',
    features: ['Business feasibility review', 'Launch planning', 'Entity selection', 'Startup readiness support'],
    icon: 'Target',
  },
  {
    id: 'business-establishment-registration',
    title: 'Business Establishment and Registration Services',
    short: 'Confident support for company registration, setup, and statutory onboarding.',
    long: 'Our establishment and registration services simplify the administrative process of launching a compliant business operation in the right legal and commercial format.',
    features: ['Registration support', 'Company setup', 'Documentation coordination', 'Compliance onboarding'],
    icon: 'Building2',
  },
  {
    id: 'tax-compliance-support',
    title: 'Tax Compliance Support',
    short: 'Guidance to keep businesses aligned with dynamic tax obligations and reporting standards.',
    long: 'We help organizations manage tax compliance obligations effectively, reduce operational friction, and strengthen reporting discipline.',
    features: ['Tax compliance review', 'Reporting support', 'Obligation mapping', 'Risk reduction'],
    icon: 'TrendingUp',
  },
  {
    id: 'intermediation-and-negotiation',
    title: 'Intermediation and Negotiation',
    short: 'Structured support for facilitating discussions and resolving commercial friction constructively.',
    long: 'We support parties through sensitive negotiations, structured mediation-style interventions, and deal positioning that protects value and preserves relationships.',
    features: ['Stakeholder alignment', 'Negotiation strategy', 'Mediation support', 'Commercial facilitation'],
    icon: 'Shield',
  },
  {
    id: 'cross-cultural-services',
    title: 'Cross-Cultural Services',
    short: 'Advice that helps organizations navigate diverse market environments and stakeholder expectations.',
    long: 'We help businesses operate effectively across cultural contexts by aligning commercial decision-making with context-sensitive communication and governance practices.',
    features: ['Cultural context analysis', 'Stakeholder mapping', 'Cross-border communication', 'Relationship management'],
    icon: 'Cpu',
  },
  {
    id: 'standard-operating-procedures',
    title: 'Standard Operating Procedures',
    short: 'Clear operating frameworks that improve consistency, control, and execution quality.',
    long: 'We help organizations develop practical SOPs that standardize workflows, reduce ambiguity, and support sustainable growth.',
    features: ['Process mapping', 'Workflow standardization', 'Control design', 'Operational consistency'],
    icon: 'Shield',
  },
  {
    id: 'value-for-money-services',
    title: 'Value for Money Services',
    short: 'Commercial assurance that helps clients maximize outcomes from resources and investments.',
    long: 'We assess resource allocation, delivery efficiency, and economic value to help organizations make decisions that are both efficient and defensible.',
    features: ['Efficiency review', 'Resource optimization', 'Value assessment', 'Commercial assurance'],
    icon: 'TrendingUp',
  },
  {
    id: 'public-private-partnerships',
    title: 'Public Private Partnerships',
    short: 'Strategic advisory for structuring and implementing sustainable public-private collaborations.',
    long: 'We support PPP development with commercial, governance, and implementation insight to help public and private partners deliver impactful outcomes.',
    features: ['PPP structuring', 'Governance design', 'Risk allocation', 'Implementation planning'],
    icon: 'Target',
  },
  {
    id: 'sector-reviews',
    title: 'Sector reviews',
    short: 'Insightful review of market conditions, trends, and operating dynamics within a sector.',
    long: 'Our sector reviews provide clear perspectives on competitive patterns, policy signals, opportunities, and strategic implications for decision-makers.',
    features: ['Market review', 'Trend assessment', 'Competitive analysis', 'Opportunity mapping'],
    icon: 'Cpu',
  },
  {
    id: 'strategic-planning-and-reform',
    title: 'Strategic Planning and Reform',
    short: 'Support for organizational redesign, strategic repositioning, and reform initiatives.',
    long: 'We help institutions and enterprises define forward-looking strategy, align leadership priorities, and implement changes that strengthen future performance.',
    features: ['Strategic planning', 'Reform design', 'Institutional review', 'Change roadmaps'],
    icon: 'Target',
  },
  {
    id: 'institutional-capacity-building',
    title: 'Institutional Capacity Building',
    short: 'Capability development that strengthens systems, teams, and governance performance.',
    long: 'We support organizations in building durable internal capability through leadership alignment, systems development, and skills-focused advisory.',
    features: ['Capability assessment', 'Leadership support', 'Team development', 'Governance strengthening'],
    icon: 'Shield',
  },
];

export const briefs = [
  {
    id: 'navigating-regulatory-change',
    title: 'Navigating Regulatory Change in the Financial Sector',
    excerpt: 'As regulatory frameworks continue to evolve, financial institutions must adopt proactive compliance strategies. This brief examines emerging trends and offers practical guidance for staying ahead of regulatory shifts.',
    category: 'Legal Services',
    date: 'December 12, 2024',
    author: 'Dr. Marcus Shawbell',
    readTime: '8 min read',
  },
  {
    id: 'strategic-ma-considerations',
    title: 'Strategic Considerations for M&A in Emerging Markets',
    excerpt: 'Emerging markets present unique opportunities and challenges for M&A activity. Understanding local regulatory environments, cultural dynamics, and market structures is essential for successful cross-border transactions.',
    category: 'Business Advisory',
    date: 'November 28, 2024',
    author: 'Dr. Marcus Shawbell',
    readTime: '12 min read',
  },
  {
    id: 'digital-transformation-governance',
    title: 'Governance Frameworks for Digital Transformation',
    excerpt: 'Effective governance is the cornerstone of successful digital transformation. This brief explores how organizations can establish robust governance frameworks that balance innovation with risk management.',
    category: 'Business Advisory',
    date: 'November 15, 2024',
    author: 'Dr. Marcus Shawbell',
    readTime: '10 min read',
  },
  {
    id: 'corporate-compliance-best-practices',
    title: 'Corporate Compliance Best Practices for 2025',
    excerpt: 'With new regulatory requirements on the horizon, organizations must revisit their compliance programs. This comprehensive guide outlines the essential elements of an effective corporate compliance framework.',
    category: 'Legal Services',
    date: 'October 30, 2024',
    author: 'Dr. Marcus Shawbell',
    readTime: '15 min read',
  },
  {
    id: 'risk-management-frameworks',
    title: 'Enterprise Risk Management: A Modern Framework',
    excerpt: 'Traditional risk management approaches are insufficient for today\'s complex business environment. This brief presents a modern, integrated framework for enterprise-wide risk identification and mitigation.',
    category: 'Business Advisory',
    date: 'October 18, 2024',
    author: 'Dr. Marcus Shawbell',
    readTime: '11 min read',
  },
];

export const people = [
  {
    id: 'phyllis-christian ',
    name: 'Phyllis M. Christian',
    role: 'Managing Consultant & Founder',
    bio: 'Listed as a leading legal practitioner in the International Who\'s Who of Corporate and Energy Lawyers. Services have been delivered to clients ranked on the Fortune 500 and Forbes Global 2000, plus the World\'s Largest Retailer (Amazon.com), and the firm is a member of the Business Council for Africa.',
    specialties: ['Corporate Law', 'M&A Strategy', 'Regulatory Compliance', 'Board Advisory'],
    isFounder: true,
  },
  {
    id: 'elena-vasquez',
    name: 'Elena Vasquez',
    role: 'Senior Legal Consultant',
    bio: 'Elena Vasquez specializes in commercial litigation and regulatory compliance, with a distinguished career representing major corporations in complex disputes. Her strategic approach to litigation consistently delivers favorable outcomes while minimizing business disruption.',
    specialties: ['Commercial Litigation', 'Regulatory Compliance', 'Arbitration'],
  },
  {
    id: 'james-okonkwo',
    name: 'James Okonkwo',
    role: 'Senior Business Advisor',
    bio: 'James Okonkwo brings extensive experience in financial advisory and risk management, having guided organizations through complex restructuring, capital optimization, and enterprise risk implementations across multiple industries.',
    specialties: ['Financial Advisory', 'Risk Management', 'Corporate Restructuring'],
  },
  {
    id: 'sarah-chen',
    name: 'Sarah Chen',
    role: 'Digital Strategy Lead',
    bio: 'Sarah Chen leads our Digital Transformation practice, combining deep technical expertise with strategic business insight. She has successfully guided numerous organizations through comprehensive digital transformation programs.',
    specialties: ['Digital Transformation', 'Technology Strategy', 'Change Management'],
  },
];

export const partners = [
  'Meridian Capital Group',
  'Atlas Regulatory Associates',
  'Pinnacle Strategic Partners',
  'Vanguard Compliance Solutions',
  'Summit Financial Advisory',
  'Horizon Legal Network',
];

export const accolades = [
  { title: 'Best in Law Consulting Firm', org: 'Oil and Gas Ghana Industry (OGGA) Awards', year: '2014–2016' },
  { title: 'Consultancy Company of the Year', org: 'Ghana Oil and Gas Awards (GOGA)', year: '2016' },
];
